# Generated by Django 3.2.11 on 2023-12-16 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passwrod', models.CharField(max_length=128, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('date', models.DateField(blank=True, max_length=64, null=True, verbose_name='出生日期')),
                ('email', models.CharField(blank=True, max_length=64, null=True, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Illustrator',
            fields=[
                ('illustrator_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('date', models.DateField(blank=True, max_length=64, null=True, verbose_name='出生日期')),
                ('email', models.CharField(blank=True, max_length=64, null=True, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('address', models.CharField(max_length=64, null=True, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, verbose_name='类型')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('count', models.CharField(blank=True, max_length=64, null=True, verbose_name='卷数')),
                ('update', models.SmallIntegerField(blank=True, choices=[(1, '更新完'), (0, '未更新完')], null=True, verbose_name='是否更新完')),
                ('date', models.DateField(blank=True, max_length=64, null=True, verbose_name='出版日期')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.author', verbose_name='作者')),
                ('illustrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.illustrator', verbose_name='插画师')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.publisher', verbose_name='出版社')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.type', verbose_name='类型')),
            ],
        ),
    ]
