# Generated by Django 3.2.11 on 2023-12-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='LightNovel',
        ),
    ]
