# Generated by Django 3.2.11 on 2023-12-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20231216_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
    ]
