# Generated by Django 3.2.11 on 2023-12-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_publisher_introduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='passwrod',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='illustrator',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='lightnovel',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(max_length=64, unique=True, verbose_name='类型'),
        ),
    ]
