# Generated by Django 3.2.11 on 2023-12-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20231217_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date',
            field=models.DateField(blank=True, max_length=64, null=True, verbose_name='出生时间'),
        ),
        migrations.AlterField(
            model_name='illustrator',
            name='date',
            field=models.DateField(blank=True, max_length=64, null=True, verbose_name='出生时间'),
        ),
    ]
