# Generated by Django 3.2.11 on 2023-12-18 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_lightnovel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightnovel',
            name='introduction',
        ),
    ]
