# Generated by Django 3.2.11 on 2023-12-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_remove_lightnovel_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightnovel',
            name='update',
            field=models.SmallIntegerField(blank=True, choices=[(1, '完结'), (0, '未完结')], null=True, verbose_name='是否更新完'),
        ),
    ]
