# Generated by Django 3.2.11 on 2023-12-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_lightnovel_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightnovel',
            name='image',
            field=models.ImageField(default='default.png', upload_to='image/'),
        ),
    ]
