# Generated by Django 3.2.11 on 2023-12-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_alter_lightnovel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightnovel',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='lightnovel',
            name='image',
            field=models.ImageField(default='default.png', upload_to='image'),
        ),
    ]
