# Generated by Django 3.2.11 on 2023-12-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_alter_lightnovel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightnovel',
            name='image',
            field=models.FileField(default='image/default.png', upload_to='image', verbose_name='封面'),
        ),
    ]
