# Generated by Django 3.2.11 on 2023-12-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_auto_20231218_1854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='User',
        ),
    ]
