# Generated by Django 3.2.11 on 2023-12-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_rename_admin_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='account',
        ),
    ]
